src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_c;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message = "Le champ ne doit pas être vide")
     */
    private $content;


    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_user;

    /**
     * @ORM\ManyToOne(targetEntity=Tricks::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_trick;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateC(): ?\DateTimeInterface
    {
        return $this->date_c;
    }

    public function setDateC(\DateTimeInterface $date_c): self
    {
        $this->date_c = $date_c;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }


    public function getFkUser(): ?User
    {
        return $this->fk_user;
    }

    public function setFkUser(?User $fk_user): self
    {
        $this->fk_user = $fk_user;

        return $this;
    }

    public function getFkTrick(): ?tricks
    {
        return $this->fk_trick;
    }

    public function setFkTrick(?tricks $fk_trick): self
    {
        $this->fk_trick = $fk_trick;

        return $this;
    }
}

src/Entity/Tricks.php
<?php

namespace App\Entity;

use App\Repository\TricksRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Validator\Constraints as TricksAssert;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=TricksRepository::class)
 * @UniqueEntity(fields="title", message="Ce trick existe déjà dans la base de données.")
 */
class Tricks
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     * @Assert\NotBlank(message = "Le champ ne doit pas être vide")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Le nom de la figure doit contenir au moins {{ limit }} caractères",
     *      maxMessage = "Le nom de la figure doit contenir au maximum {{ limit }} caractères",
     *      allowEmptyString = false
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message = "Le champ ne doit pas être vide")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_c;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_modification;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pictures;

    /**
     * @ORM\Column(type="integer")
     */
    private $last_user_modification;


    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_author;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $videos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover;

    protected $tags;

    /**
     * @ORM\ManyToOne(targetEntity=CategoryRef::class, inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_group;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message = "Le champ ne doit pas être vide")
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $difficulty;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="fk_trick", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;


    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateC(): ?\DateTimeInterface
    {
        return $this->date_c;
    }

    public function setDateC(\DateTimeInterface $date_c): self
    {
        $this->date_c = $date_c;

        return $this;
    }

    public function getLastModification(): ?\DateTimeInterface
    {
        return $this->last_modification;
    }

    public function setLastModification(\DateTimeInterface $last_modification): self
    {
        $this->last_modification = $last_modification;

        return $this;
    }

    public function getPictures()
    {
        return $this->pictures;
    }

    public function setPictures($pictures)
    {
        $this->pictures = $pictures;

        return $this;
    }

    public function getLastUserModification(): ?int
    {
        return $this->last_user_modification;
    }

    public function setLastUserModification(int $last_user_modification): self
    {
        $this->last_user_modification = $last_user_modification;

        return $this;
    }


    public function getFkAuthor(): ?User
    {
        return $this->fk_author;
    }

    public function setFkAuthor(?User $fk_author): self
    {
        $this->fk_author = $fk_author;

        return $this;
    }


    public function getVideos(): ?string
    {
        return $this->videos;
    }

    public function setVideos(?string $videos): self
    {
        $this->videos = $videos;

        return $this;
    }


    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getTags()
    {
        return $this->tags;
    }

    public function getFkGroup(): ?CategoryRef
    {
        return $this->fk_group;
    }

    public function setFkGroup(?CategoryRef $fk_group): self
    {
        $this->fk_group = $fk_group;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getDifficulty(): ?string
    {
        return $this->difficulty;
    }

    public function setDifficulty(string $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */

    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setFkTrick($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getFkTrick() === $this) {
                $comment->setFkTrick(null);
            }
        }

        return $this;
    }


}

src/Controller/handler/tricks/HandlerNewTrick.php
<?php


namespace App\Controller\handler\tricks;


use App\Controller\TricksController;
use App\Entity\CategoryRef;
use App\Entity\Tricks;
use App\Entity\User;
use App\Form\TricksType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Routing\Annotation\Route;


class HandlerNewTrick extends AbstractController
{

    private $form;
    private $request;
    private $slugger;
    private $validator;
    private $user;
    private $trick;
    private $uploaddir;


    public function __construct()
    {
        $this->user = new User();
    }


    public function setForm($form)
    {
        $this->form = $form;
    }

    public function getForm()
    {
        return $this->form;
    }

    public function setRequest($request)
    {
        $this->request = $request;
    }

    public function getRequest()
    {
        return $this->request;
    }

    public function setTrick($trick)
    {
        $this->trick = $trick;
    }

    public function getTrick()
    {
        return $this->trick;
    }

    public function setSlugger($slugger)
    {
        $this->slugger = $slugger;
    }

    public function getSlugger()
    {
        return $this->slugger;
    }

    public function setValidator($validator)
    {
        $this->slugger = $validator;
    }

    public function getValidator()
    {
        return $this->validator;
    }

    public function setUploadDir($uploaddir)
    {
        return $this->uploaddir = $uploaddir;
    }


    public function myCheckForm()
    {
            $erreur = false;
            $message = "";
            $extensions = array("jpg","png","jpeg");
            $verifCover = $this->form->get('cover')->getData();
            $pictures = $this->form->get('pictures')->getData();


            if(empty($verifCover))
            {
                $erreur = true;
                $message = "L'image pour la figure est vide. Veuillez selectionnez une image";
            }

            if(!empty($verifCover) || $verifCover !== null)
            {

                if(!in_array(strtolower($verifCover->guessExtension()),$extensions))
                {
                    $erreur = true;
                    $message ="L'extension n'est pas valide. veuillez choisir une extension valide parmi : png, jpg, jpeg";
                }

                if($verifCover->getSize() > 2000000)
                {
                    $erreur = true;
                    $message = "warning', 'La taille du fichier est trop grande. la limite est de 2 mo";
                }
            }

            foreach ($pictures as $file)
            {
                if(!in_array(strtolower($file->guessExtension()),$extensions))
                {
                    $erreur = true;
                    $message ="Une extension n'est pas valide. veuillez choisir une extension valide parmi : png, jpg, jpeg";
                }
                if($file->getSize() > 2000000)
                {
                    $erreur = true;
                    $message = "warning', 'La taille du fichier est trop grande. la limite est de 2 mo";
                }
            }

            /*if(!empty($this->form->get('videos')->getData()))
            {
                $videos = $this->form->get('videos')->getData();
                $videos = explode(";",$videos);

                foreach ($videos as $video)
                {
                    if(!preg_match('/(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/i',$video))
                    {
                        $erreur = true;
                        $message = "Une video n'est pas au bon format";
                    }
                }
            }*/



        return $array = array('erreur'=>$erreur,'errorMessage'=>$message);
    }

    function SubmitForm($session)
    {
        $mycheckform = $this->myCheckForm();

        if ($this->form->isValid() && $mycheckform["erreur"] === false)
        {
            $timezone = new \DateTimeZone('Europe/Paris');
            $this->trick->setLastModification(new \DateTime('now', $timezone));
            $this->trick->setDateC(new \DateTime('now', $timezone));
            $this->trick->setLastUserModification($session->getId());
            $this->trick->setFkAuthor($session);
            $this->trick->setSlug($this->form->get("title")->getData());


            // upload videos
            $getVideos = $this->form->get('videos')->getData();
            if(!empty($this->form->get('videos')->getData()))
            {
                $exVideos = explode(";",$getVideos);
                $Videos = serialize($exVideos);
                $this->trick->setVideos($Videos);
            }
            else
            {
                $this->trick->setVideos(NULL);
            }

            // cover

            $newCover = $this->addnewCover($this->form->get('cover')->getData());
            $this->trick->setCover($newCover);

            // ================= ajout des nouvelles images

            $newFilename = $this->addnewPictures($this->form->get('pictures')->getData());
            // set images

            if(!empty($newFilename))
            {
                $listImages = serialize($newFilename);
                $this->trick->setPictures($listImages);
            }
            else
            {
                $listImages = NULL;
                $this->trick->setPictures($listImages);
                //$newFilename = serialize($newFilename);
            }

            return true;

        }else
        {
            return false;
        }

    }


    public function addnewPictures($pictures)
    {
        if(!empty($pictures))
        {

            $files = $pictures; // recuperation des données get pictures du formulaire soumis

            //dd($files);
            foreach ($files as $key => $file)
            {

                $originalFilename[$key] = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename[$key] = $this->slugger->slug($originalFilename[$key]);
                $newFilename[$key] = $safeFilename[$key] . '-' . uniqid() . '.' . $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try
                {
                    $file->move(
                        $this->uploaddir,
                        $newFilename[$key]
                    );
                }
                catch (FileException $e)
                {
                    // ... handle exception if something happens during file upload
                }

                $Allfiles = [];

            }
            return $newFilename;
        }
    }
//======= class a pars ==============
    private function addnewCover($addcover)
    {
        // cover
        $cover = $addcover; // recuperation des données get pictures du formulaire soumis

        //dump($this->slugger);exit;
        $originalFilename1 = pathinfo($cover->getClientOriginalName(), PATHINFO_FILENAME);
        $safeFilename1 = $this->slugger->slug($originalFilename1);
        $newCover = $safeFilename1.'-'.uniqid().'.'.$cover->guessExtension();

        // Move the file to the directory where brochures are stored
        try
        {
            $cover->move(
                $this->uploaddir,
                $newCover
            );
        }
        catch (FileException $e)
        {
            // ... handle exception if something happens during file upload
        }

        return $newCover;
    }


}

templates/tricks/_delete_form.html.twig
<form method="post" action="{{ path('tricks_delete', {'id': trick.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
    <button class="btn btn-danger">Supprimer cette article</button>
</form>

templates/tricks/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des figures{% endblock %}

{% block body %}
    {% include 'header.html.twig' %}
    <h1>Liste des figures</h1>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    <a style="text-align: center;display:block;" href="{{ path('tricks_new') }}">Créer une nouvelle figure</a>
    <table class="table table-striped"><br><br>
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom</th>
                <th scope="col">Description</th>
                {#<th>Date_c</th>
                <th>Last_modification</th>#}
                <th scope="col">Images</th>
                <th scope="col">Last_user_modification</th>
                <th scope="col">Fk_author</th>
                <th scope="col">Fk_group</th>
                <th scope="col">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for trick in tricks %}
            <tr>
                <td>{{ trick.id }}</td>
                <td>{{ trick.title }}</td>
                <td>{{ trick.description }}</td>
                {#<td>{{ trick.dateC ? trick.dateC|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ trick.lastModification ? trick.lastModification|date('Y-m-d H:i:s') : '' }}</td>#}
                <td>{{ trick.pictures }}</td>
                <td>{{ trick.lastUserModification }}</td>
                <td>{{ trick.fkAuthor }}</td>
                <td>{{ trick.fkGroup }}</td>
                <td>
    <a href="{{ path('tricks_show', {'slug': trick.slug}) }}">Voir</a>
    <a href="{{ path('tricks_edit', {'id': trick.id}) }}">Modifier</a>
</td>
</tr>
{% else %}
<tr>
<td colspan="10">no records found</td>
</tr>
{% endfor %}
</tbody>
</table>


{% endblock %}

templates/tricks/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Figure{% endblock %}

{% block body %}
    {% include 'header.html.twig' %}

    <!-- Page Content -->

    {% for message in app.flashes('warning') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    <div class="container">

        <div class="row">

            {% for trick in tricks %}

            <!-- Post Content Column -->
            <div class="col-lg-12">

                <!-- Title -->
                <h1 class="mt-4">{{ trick.title }}</h1>

                <hr>

                <!-- Date/Time -->
                <p>Dernière modification le  {{ trick.lastModification ? trick.lastModification|date('Y-m-d H:i:s') : '' }}</p>

                <hr>

                <!-- Preview Image -->
                <div style="width:100%;height:400px;">
                    <img style="object-fit: cover;width:100%;height:400px;" class="img-fluid rounded" src="/uploads/{{ trick.cover }}" alt="">
                </div>

                <hr>
                {% if app.user %}
                {{ include('tricks/_delete_form.html.twig') }}
                {% endif %}
                <br>
                <!-- Medias -->

                <div class="card my-4 ">
                    <h5 class="card-header">Medias</h5>
                    <div class="medias">
                        <!-- image -->

                        {% for picture in allPictures %}
                        <div class="media" style="height:150px;width:250px;margin:10px">
                            <a href="/uploads/{{ picture }}">
                                <img  style="height:150px;width:250px;" class="img-fluid rounded" src="/uploads/{{ picture }}" alt="" />
                            </a>
                        </div>
                        {% endfor %}

                        <!-- videos -->
                        {% for video in allVideos %}
                        <div class="media" style="margin: 10px;" >
                            <iframe width="250px" height="auto" src="{{video}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                        {% endfor %}


                    </div>
                    <div style="display:flex;justify-content: center;margin: 20px">
                        <button type="button" etat="close" id="showmedia" class="btn btn-primary" data-type="+">Voir média</button>
                    </div>

                </div>

                <!-- Post Content -->


                <p>{{ trick.description }}</p>
                <p style="font-weight: bold;">Groupe de la figure : {{ categorieFigure.name }}</p>

                <br>
                <p>Crée le : {{ trick.dateC ? trick.dateC|date('Y-m-d H:i:s') : '' }} par {{ trick.fkAuthor.lastname }} {{ trick.fkAuthor.firstname }}</p>
                <hr>

                <div class="card my-4">
                    <h5 class="card-header">Commentaires :</h5>
                    <div  class="card-body">
                        <!-- Single Comment -->
                        {% for comment in comments %}
                            <div style="display:flex;justify-content: space-between;">
                            <div class="media mb-4 commentaire">
                                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                                <div class="media-body">
                                    {% if comment %}
                                    <h5 class="mt-0">{{ comment.fkUser.firstname }} {{ comment.fkUser.lastname }}</h5>
                                    <p>Publié le {{ comment.DateC ? comment.DateC|date('d-m-Y à H:i:s')}}  </p><br>
                                    {{ comment.content }}.
                                    {% else %}
                                        <p>il n'y a aucun commentaire(s) pour le moment</p>
                                    {% endif %}
                                </div>

                            </div>
                            {% if app.user %}
                            {% if comment.fkUser.id == app.user.id %}
                            <div>
                                <form method="post" action="{{ path('comments_delete', {'id': comment.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire?');">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
                                    <button style="background-color:#FFF;border: none;color:red;cursor: pointer;" class="">Supprimer mon commentaire</button>
                                </form>
                            </div>

                            {% endif %}
                            {% endif %}

                            </div>
                            <hr><br>
                        {% endfor %}
                    </div>
                    {#
                    <div style="display:flex;justify-content: center;margin-bottom: 20px">
                        <button type="button" id="showmore" class="btn btn-primary" data-type="+">Voir plus</button>
                    </div>
                    #}
                </div>



                {% if app.user %}
                <!-- Comments Form -->
                <div class="card my-4">
                    <h5 class="card-header">Laisser un commentaire :</h5>
                    <div class="card-body">
                        {{ form_start(form) }}
                        {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
                        <br>
                        <button type="submit" class="btn btn-primary">Commenter</button>
                        {{ form_end(form) }}

                    </div>
                </div>

                {% endif %}

            </div>

        </div>
        <!-- /.row -->
                <div style="width: 100px;margin:auto;">
                    {{ knp_pagination_render(comments) }}
                </div>
    </div>


            {% endfor %}
{% endblock %}
{% block javascripts %}
    <script>
        //alert("ok");
        $nbCommentaire = $(".commentaire").length;
        //alert($nbCommentaire);
        if($nbCommentaire > 10){
            $("#showmore").show();
        }else{
            $("#showmore").hide();
        }

        new ShowMoreShowLess(".commentaire","#showmore","Voir plus","Voir moins",10,10);





// bouton see medias

        function seeMedias(){
            let tailleFenetre = $(document).width();
            tailleFenetre = parseInt(tailleFenetre);
            if(tailleFenetre > 600){
                $(".medias").removeClass("mediasOff");
                $(".medias").addClass("mediasOn");

            }else{
                $(".medias").removeClass("mediasOn");
                $(".medias").addClass("mediasOff");
            }
        }
        seeMedias();
        $(window).on("resize",function(){
            //alert("ok");
            seeMedias();
        });

        $("#showmedia").click(function(){
            let etat = $(this).attr("etat");
            //alert(etat);
            if(etat === "close"){
                $(this).attr("etat","open");
                $(this).html("Cacher");
                $(".medias").removeClass("mediasOff");
                $(".medias").addClass("mediasOn");
            }else{
                $(this).attr("etat","close");
                $(this).html("Voir médias");
                $(".medias").removeClass("mediasOn");
                $(".medias").addClass("mediasOff");
            }

        });

        //alert(test);

    </script>
{% endblock %}